version: '3'
services: 
  ollama-container:
    container_name: ollama-container
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - "11434:11434"

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - ollama-container
    

